import { useState } from "react";

const T="#2DD4A8",S="#0c0c0e",C="#111113",B="#27272a",M="#71717a",X="#e4e4e7";

function Ic({n,s=16}){const p={
key:<path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.78 7.78 5.5 5.5 0 0 1 7.78-7.78zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"/>,
bot:<><rect x="3" y="8" width="18" height="12" rx="3"/><path d="M12 8V5"/><circle cx="12" cy="3" r="2"/><path d="M9 15h.01m5.99 0h.01"/></>,
phone:<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/>,
zap:<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>,
check:<path d="M20 6L9 17l-5-5"/>,
chev:<path d="M9 18l6-6-6-6"/>,
upload:<><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></>,
search:<><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></>,
filter:<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>,
play:<polygon points="5 3 19 12 5 21 5 3"/>,
pause:<><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></>,
bar:<><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></>,
users:<><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></>,
building:<><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01M16 6h.01M8 10h.01M16 10h.01M8 14h.01M16 14h.01"/></>,
link:<><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></>,
eye:<><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></>,
settings:<><circle cx="12" cy="12" r="3"/><path d="M12 1v2m0 18v2m-9-11h2m18 0h2m-4.22-5.78l-1.42 1.42M5.64 18.36l-1.42 1.42m0-13.56l1.42 1.42m12.72 12.72l1.42 1.42"/></>,
x:<><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></>,
clock:<><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></>,
};return <svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{p[n]}</svg>;}

function Bd({children,color}){const c={green:{bg:"#16653420",t:"#4ade80"},blue:{bg:"#1e40af20",t:"#60a5fa"},purple:{bg:"#5b21b620",t:"#a78bfa"},red:{bg:"#7f1d1d20",t:"#ef4444"},amber:{bg:"#78350f20",t:"#f59e0b"},teal:{bg:`${T}15`,t:T},gray:{bg:"#27272a",t:"#a1a1aa"}}[color]||{bg:"#27272a",t:"#a1a1aa"};return <span style={{fontSize:"10px",padding:"2px 8px",borderRadius:"4px",background:c.bg,color:c.t,fontWeight:500}}>{children}</span>;}

function Fr({title,sub,children}){return(<div style={{background:C,border:`1px solid ${B}`,borderRadius:"16px",overflow:"hidden"}}><div style={{padding:"10px 16px",borderBottom:`1px solid ${B}`,display:"flex",alignItems:"center",gap:"8px"}}><div style={{display:"flex",gap:"6px"}}>{["#ff5f57","#ffbd2e","#28c840"].map(c=><div key={c} style={{width:"10px",height:"10px",borderRadius:"50%",background:c,opacity:0.7}}/>)}</div><div style={{flex:1,textAlign:"center"}}><span style={{fontSize:"11px",color:M}}>{title}</span></div></div><div style={{padding:"20px"}}>{sub&&<div style={{fontSize:"11px",color:"#3f3f46",marginBottom:"16px"}}>{sub}</div>}{children}</div></div>);}

function Sl({children}){return <div style={{fontSize:"10px",fontWeight:600,letterSpacing:"1.5px",textTransform:"uppercase",color:T,margin:"32px 0 12px",display:"flex",alignItems:"center",gap:"8px"}}><div style={{width:"16px",height:"1px",background:T}}/>{children}</div>;}

function F1(){return(<Fr title="/dashboard/setup" sub="Feature 1 — Setup wizard onboarding (Step 1: Connect providers)">
<div style={{display:"flex",alignItems:"center",gap:"0",marginBottom:"24px",padding:"0 16px"}}>{["Connect providers","Create agent","Import number","Test call"].map((l,i)=>(<div key={l} style={{display:"flex",alignItems:"center",flex:i<3?1:"none"}}><div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"4px"}}><div style={{width:"28px",height:"28px",borderRadius:"50%",background:i===0?`${T}18`:S,border:i===0?`1.5px solid ${T}`:`1px solid ${B}`,display:"flex",alignItems:"center",justifyContent:"center",color:i===0?T:"#3f3f46",fontSize:"11px",fontWeight:500}}>{i+1}</div><span style={{fontSize:"9px",color:i===0?X:"#3f3f46"}}>{l}</span></div>{i<3&&<div style={{flex:1,height:"1px",background:B,margin:"0 6px",marginBottom:"16px"}}/>}</div>))}</div>
<div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"16px"}}><div style={{width:"32px",height:"32px",borderRadius:"8px",background:`${T}0a`,display:"flex",alignItems:"center",justifyContent:"center",color:T}}><Ic n="key" s={16}/></div><div><div style={{fontSize:"16px",fontWeight:600,color:"#fafafa"}}>Connect your AI providers</div><div style={{fontSize:"12px",color:M}}>Add API keys for LLM, ASR, and TTS services</div></div></div>
{[{l:"LLM provider",ps:["OpenAI","Anthropic","Gemini"],a:"OpenAI"},{l:"Speech recognition",ps:["Deepgram","Google STT","Azure"],a:null},{l:"Voice synthesis",ps:["ElevenLabs","Azure TTS","Google"],a:null}].map(s=>(<div key={s.l} style={{background:S,border:`1px solid ${B}`,borderRadius:"10px",padding:"14px",marginBottom:"8px"}}><div style={{fontSize:"12px",fontWeight:500,color:"#d4d4d8",marginBottom:"8px"}}>{s.l}</div><div style={{display:"flex",gap:"6px",marginBottom:"8px",flexWrap:"wrap"}}>{s.ps.map(p=><div key={p} style={{padding:"4px 10px",fontSize:"11px",borderRadius:"5px",border:s.a===p?`1px solid ${T}`:`1px solid ${B}`,background:s.a===p?`${T}0a`:C,color:s.a===p?T:"#a1a1aa"}}>{p}</div>)}</div><div style={{padding:"8px 10px",fontSize:"11px",borderRadius:"6px",border:`1px solid ${B}`,background:C,color:"#52525b",fontFamily:"monospace"}}>{s.a?"sk-proj-xxxxx...":"API key..."}</div>{s.a&&<div style={{marginTop:"5px",fontSize:"10px",color:T}}>Key saved</div>}</div>))}
<div style={{display:"flex",justifyContent:"space-between",marginTop:"16px",alignItems:"center"}}><span style={{fontSize:"11px",color:"#3f3f46",textDecoration:"underline"}}>Skip setup</span><div style={{padding:"8px 18px",fontSize:"12px",fontWeight:500,borderRadius:"7px",background:T,color:S,display:"flex",alignItems:"center",gap:"4px"}}>Continue <Ic n="chev" s={12}/></div></div>
</Fr>);}

function F2(){return(<Fr title="/dashboard/campaign/new" sub="Feature 2 — Campaign stepper (Step 2: Upload contacts)">
<div style={{display:"flex",gap:"3px",marginBottom:"20px"}}>{["Details","Contacts","Schedule","Review"].map((s,i)=><div key={s} style={{flex:1,textAlign:"center",padding:"7px 0",fontSize:"11px",fontWeight:500,borderBottom:`2px solid ${i<=1?T:B}`,color:i<=1?X:"#3f3f46"}}>{s}</div>)}</div>
<div style={{border:`2px dashed ${B}`,borderRadius:"10px",padding:"24px",textAlign:"center",marginBottom:"12px"}}><div style={{color:"#3f3f46",marginBottom:"6px"}}><Ic n="upload" s={24}/></div><div style={{fontSize:"12px",color:X}}>Drag and drop your CSV file here</div><div style={{fontSize:"10px",color:M}}>Max 25MB / 50,000 rows</div></div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",overflow:"hidden",marginBottom:"12px"}}><div style={{padding:"8px 12px",borderBottom:`1px solid ${B}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:"11px",fontWeight:500,color:X}}>contacts_april.csv — 1,247 rows</span><Bd color="teal">Valid</Bd></div>
<table style={{width:"100%",fontSize:"10px",borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${B}`}}>{["phone_number","name","appointment_time"].map(h=><th key={h} style={{padding:"6px 12px",textAlign:"left",color:M,fontWeight:500}}>{h}</th>)}</tr></thead><tbody>{[["+19168888860","John Doe","Apr 15 10:00 AM"],["+19168888861","Jane Smith","Apr 15 11:00 AM"],["+19168888862","Bob Wilson","Apr 15 2:00 PM"]].map((r,i)=><tr key={i} style={{borderBottom:`1px solid ${B}`}}>{r.map((c,j)=><td key={j} style={{padding:"6px 12px",color:j===0?T:"#d4d4d8"}}>{c}</td>)}</tr>)}</tbody></table></div>
<div style={{display:"flex",justifyContent:"space-between"}}><div style={{padding:"7px 16px",fontSize:"12px",borderRadius:"7px",border:`1px solid ${B}`,color:"#a1a1aa"}}>Back</div><div style={{padding:"7px 16px",fontSize:"12px",fontWeight:500,borderRadius:"7px",background:T,color:S,display:"flex",alignItems:"center",gap:"4px"}}>Continue <Ic n="chev" s={12}/></div></div>
</Fr>);}

function F3(){return(<Fr title="/dashboard/agents/agent_001/edit" sub="Feature 3 — Agent editor with inline test panel + status bar">
<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 12px",background:S,borderRadius:"8px",marginBottom:"12px",border:`1px solid ${B}`}}>
<div style={{display:"flex",alignItems:"center",gap:"8px"}}><span style={{fontSize:"14px",fontWeight:600,color:"#fafafa"}}>Sales Qualifier v1</span><Bd color="green">Published</Bd><span style={{fontSize:"10px",color:"#3f3f46"}}>2h ago</span></div>
<div style={{display:"flex",gap:"6px"}}><div style={{padding:"5px 12px",fontSize:"11px",borderRadius:"5px",border:`1px solid #f59e0b40`,color:"#f59e0b"}}>Pause</div><div style={{padding:"5px 12px",fontSize:"11px",borderRadius:"5px",background:T,color:S}}>Save</div></div></div>
<div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr",gap:"10px"}}>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"10px",padding:"14px"}}>
<div style={{display:"flex",gap:"1px",marginBottom:"12px",background:B,borderRadius:"5px",overflow:"hidden"}}>{["Prompt","Models","Advanced","Actions"].map((t,i)=><div key={t} style={{flex:1,textAlign:"center",padding:"6px 0",fontSize:"11px",background:i===0?`${T}12`:C,color:i===0?T:"#52525b"}}>{t}</div>)}</div>
<div style={{fontSize:"11px",color:M,marginBottom:"4px"}}>System prompt</div>
<div style={{padding:"10px",borderRadius:"6px",border:`1px solid ${B}`,background:C,fontSize:"11px",color:"#d4d4d8",lineHeight:1.5,marginBottom:"10px",minHeight:"60px"}}>You are a friendly sales assistant for Acme Corp. Qualify leads by understanding needs, budget, timeline...</div>
<div style={{fontSize:"11px",color:M,marginBottom:"4px"}}>Greeting message</div>
<div style={{padding:"8px 10px",borderRadius:"6px",border:`1px solid ${B}`,background:C,fontSize:"11px",color:"#a1a1aa"}}>Hi! Thanks for calling Acme. How can I help?</div></div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"10px",padding:"14px"}}>
<div style={{fontSize:"12px",fontWeight:500,color:X,marginBottom:"12px",display:"flex",alignItems:"center",gap:"4px"}}><Ic n="zap" s={13}/>Test panel</div>
<div style={{textAlign:"center",padding:"12px 0"}}><div style={{width:"48px",height:"48px",borderRadius:"50%",margin:"0 auto 8px",background:`${T}12`,border:`1.5px solid ${T}40`,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{display:"flex",gap:"2px",alignItems:"flex-end",height:"14px"}}>{[6,12,8,14].map((h,i)=><div key={i} style={{width:"3px",height:`${h}px`,borderRadius:"2px",background:T}}/>)}</div></div>
<div style={{fontSize:"12px",color:X}}>Connected</div><div style={{fontSize:"10px",color:M}}>00:34</div></div>
{[{s:"Agent",t:"Hi! Thanks for calling Acme.",c:T},{s:"Caller",t:"I'm looking at your enterprise plan.",c:"#60a5fa"},{s:"Agent",t:"Great! How many seats do you need?",c:T}].map((m,i)=><div key={i} style={{display:"flex",gap:"6px",alignItems:"flex-start",marginBottom:"6px"}}><div style={{width:"4px",height:"4px",borderRadius:"50%",background:m.c,marginTop:"4px",flexShrink:0}}/><div><div style={{fontSize:"9px",color:"#3f3f46"}}>{m.s}</div><div style={{fontSize:"11px",color:"#d4d4d8",lineHeight:1.3}}>{m.t}</div></div></div>)}
</div></div>
</Fr>);}

function F4(){return(<Fr title="/dashboard/phone-numbers (side panel)" sub="Feature 4 — Provider-guided phone number setup">
<div style={{maxWidth:"340px",margin:"0 auto"}}>
<div style={{fontSize:"15px",fontWeight:600,color:"#fafafa",marginBottom:"12px"}}>Add phone number</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"6px",marginBottom:"12px"}}>
{[{n:"Twilio",c:"#F22F46",sel:true},{n:"Telnyx",c:"#00C08B"},{n:"Exotel",c:"#4F46E5"},{n:"Other SIP",c:"#64748B"}].map(p=><div key={p.n} style={{padding:"10px",borderRadius:"8px",display:"flex",alignItems:"center",gap:"8px",border:p.sel?`1.5px solid ${p.c}`:`1px solid ${B}`,background:p.sel?`${p.c}08`:C}}><div style={{width:"24px",height:"24px",borderRadius:"5px",background:`${p.c}18`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:"11px",fontWeight:600,color:p.c}}>{p.n[0]}</div><span style={{fontSize:"11px",fontWeight:500,color:X}}>{p.n}</span></div>)}</div>
<div style={{background:`${T}08`,border:`1px solid ${T}20`,borderRadius:"6px",padding:"8px 10px",fontSize:"10px",color:T,lineHeight:1.4,marginBottom:"10px"}}>SIP address auto-filled for Twilio.</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px",marginBottom:"10px"}}>{[{l:"Phone number",v:"+15541361716"},{l:"Display name",v:"Main sales line"}].map(f=><div key={f.l}><div style={{fontSize:"10px",color:M,marginBottom:"3px"}}>{f.l}</div><div style={{padding:"7px 10px",fontSize:"11px",borderRadius:"5px",border:`1px solid ${B}`,background:C,color:X}}>{f.v}</div></div>)}</div>
<div style={{fontSize:"10px",color:"#3f3f46",marginBottom:"8px"}}>▸ Advanced SIP settings</div>
<div style={{display:"flex",gap:"6px"}}>{["Verified","Unverified","Error"].map((s,i)=><div key={s} style={{display:"flex",alignItems:"center",gap:"3px",fontSize:"10px",color:i===0?"#4ade80":i===1?"#f59e0b":"#ef4444"}}><div style={{width:"5px",height:"5px",borderRadius:"50%",background:i===0?"#4ade80":i===1?"#f59e0b":"#ef4444"}}/>{s}</div>)}</div>
</div></Fr>);}

function F5(){return(<Fr title="/dashboard/analytics" sub="Feature 5 — Actionable analytics with insights bar">
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"6px",marginBottom:"12px"}}>{[{l:"Total calls",v:"2,385",ch:"+595%",u:true},{l:"Answer rate",v:"60%",ch:"-20%",u:false},{l:"Call duration",v:"686 min",ch:"+118%",u:true},{l:"Answered",v:"1,432",ch:"+476%",u:true}].map(k=><div key={k.l} style={{background:S,borderRadius:"8px",padding:"10px",border:`1px solid ${B}`}}><div style={{fontSize:"10px",color:M,marginBottom:"4px"}}>{k.l}</div><div style={{fontSize:"18px",fontWeight:600,color:"#fafafa",marginBottom:"2px"}}>{k.v}</div><div style={{fontSize:"10px",color:k.u?"#4ade80":"#ef4444"}}>{k.u?"↑":"↓"} {k.ch}</div></div>)}</div>
<div style={{background:"#f59e0b08",border:`1px solid #f59e0b20`,borderRadius:"8px",padding:"10px 12px",marginBottom:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"6px"}}>⚠ Insights</div>{["Answer rate dropped 20%. Adjust call windows to business hours.","40% No Answer. Enable voicemail detection."].map((t,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 8px",background:C,borderRadius:"5px",marginBottom:"4px"}}><span style={{fontSize:"11px",color:"#d4d4d8"}}>{t}</span><span style={{fontSize:"10px",color:T,flexShrink:0,marginLeft:"8px"}}>Fix →</span></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px"}}><div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"8px"}}>Call status</div><div style={{display:"flex",alignItems:"center",gap:"12px"}}><div style={{width:"60px",height:"60px",borderRadius:"50%",background:`conic-gradient(#4ade80 0% 58%,#60a5fa 58% 98%,#a78bfa 98% 100%)`,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:"38px",height:"38px",borderRadius:"50%",background:S,display:"flex",alignItems:"center",justifyContent:"center",fontSize:"9px",color:X,fontWeight:500}}>2,385</div></div><div style={{fontSize:"10px",color:"#a1a1aa",lineHeight:1.8}}>Answered 58%<br/>No Answer 40%<br/>Voicemail 2%</div></div></div><div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"8px"}}>Task success rate</div><svg viewBox="0 0 200 50" style={{width:"100%"}}><path d="M0 45 L40 40 L80 35 L120 22 L160 27 L200 14" fill="none" stroke={T} strokeWidth="2"/><path d="M0 45 L40 40 L80 35 L120 22 L160 27 L200 14 L200 50 L0 50Z" fill={`${T}10`}/></svg></div></div>
</Fr>);}

function F6(){return(<Fr title="/dashboard (admin view)" sub="Feature 6 — Role-based sidebar + admin impersonation">
<div style={{display:"grid",gridTemplateColumns:"180px 1fr",gap:"10px"}}>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"10px",padding:"12px"}}>
<div style={{display:"flex",alignItems:"center",gap:"6px",marginBottom:"12px",paddingBottom:"10px",borderBottom:`1px solid ${B}`}}><div style={{width:"24px",height:"24px",borderRadius:"5px",background:`${T}18`,display:"flex",alignItems:"center",justifyContent:"center",color:T,fontSize:"10px",fontWeight:600}}>AS</div><div><div style={{fontSize:"11px",fontWeight:500,color:X}}>Agent Studio</div><div style={{fontSize:"9px",color:M}}>admin</div></div></div>
<div style={{fontSize:"9px",fontWeight:500,color:"#3f3f46",letterSpacing:"0.5px",textTransform:"uppercase",marginBottom:"6px"}}>Admin portal</div>
{[{i:"building",l:"ISV Management"},{i:"users",l:"User Management",a:true},{i:"link",l:"Association"}].map(it=><div key={it.l} style={{display:"flex",alignItems:"center",gap:"6px",padding:"5px 8px",borderRadius:"5px",fontSize:"11px",marginBottom:"2px",background:it.a?`${T}0a`:"transparent",color:it.a?T:"#a1a1aa"}}><Ic n={it.i} s={12}/>{it.l}</div>)}
<div style={{height:"1px",background:B,margin:"8px 0"}}/>
<div style={{fontSize:"9px",fontWeight:500,color:"#3f3f46",letterSpacing:"0.5px",textTransform:"uppercase",marginBottom:"6px"}}>Studio</div>
{[{i:"bar",l:"Overview"},{i:"bot",l:"Agents"},{i:"phone",l:"Phone Numbers"},{i:"play",l:"Campaign"},{i:"bar",l:"Analytics"},{i:"settings",l:"Settings"}].map(it=><div key={it.l} style={{display:"flex",alignItems:"center",gap:"6px",padding:"5px 8px",borderRadius:"5px",fontSize:"11px",color:"#52525b",marginBottom:"2px"}}><Ic n={it.i} s={12}/>{it.l}</div>)}
</div>
<div>
<div style={{background:"#f59e0b15",border:`1px solid #f59e0b30`,borderRadius:"6px",padding:"6px 10px",marginBottom:"10px",display:"flex",justifyContent:"space-between",fontSize:"11px"}}><div style={{display:"flex",alignItems:"center",gap:"4px"}}><Ic n="eye" s={12}/><span style={{color:"#f59e0b"}}>Viewing as john.doe@acme.com</span></div><span style={{color:"#f59e0b",textDecoration:"underline"}}>Exit</span></div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",overflow:"hidden"}}><div style={{padding:"10px 14px",borderBottom:`1px solid ${B}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:"13px",fontWeight:600,color:"#fafafa"}}>User Management</span><div style={{padding:"4px 10px",fontSize:"10px",borderRadius:"5px",background:T,color:S}}>+ Create user</div></div>
<table style={{width:"100%",fontSize:"10px",borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${B}`}}>{["User","Role","ISV","Agora ID","Actions"].map(h=><th key={h} style={{padding:"6px 10px",textAlign:"left",color:M,fontWeight:500}}>{h}</th>)}</tr></thead><tbody>{[{u:"john@acme.com",r:"user",isv:"Acme Corp",ag:"****7890"},{u:"jane@beta.io",r:"user",isv:"Beta Inc",ag:"****4321"},{u:"admin@studio.com",r:"admin",isv:"—",ag:"—"}].map((r,i)=><tr key={i} style={{borderBottom:`1px solid ${B}`}}><td style={{padding:"6px 10px",color:X}}>{r.u}</td><td style={{padding:"6px 10px"}}><Bd color={r.r==="admin"?"purple":"gray"}>{r.r}</Bd></td><td style={{padding:"6px 10px",color:"#a1a1aa"}}>{r.isv}</td><td style={{padding:"6px 10px",color:"#52525b",fontFamily:"monospace"}}>{r.ag}</td><td style={{padding:"6px 10px"}}><span style={{color:T,fontSize:"9px"}}>Edit</span> <span style={{color:"#52525b",fontSize:"9px"}}>View as</span></td></tr>)}</tbody></table></div>
</div></div>
</Fr>);}

function F7(){const[sel,setSel]=useState(null);const calls=[{id:1,ph:"+1***8860",ag:"Sales Qualifier",dur:"2m 34s",st:"answered",out:"Task success",dt:"2h ago"},{id:2,ph:"+1***8861",ag:"Sales Qualifier",dur:"0m 12s",st:"no_answer",out:"—",dt:"2h ago"},{id:3,ph:"+1***8862",ag:"NPS Survey",dur:"1m 45s",st:"answered",out:"Task success",dt:"3h ago"},{id:4,ph:"+1***8863",ag:"Sales Qualifier",dur:"0m 08s",st:"voicemail",out:"—",dt:"3h ago"},{id:5,ph:"+1***8864",ag:"Appointment Bot",dur:"3m 12s",st:"answered",out:"Transferred",dt:"4h ago"}];const sc={answered:"green",no_answer:"blue",voicemail:"purple",failed:"red"};
return(<Fr title="/dashboard/call-history" sub="Feature 7 — Call history with transcript viewer (click a row)">
<div style={{display:"flex",gap:"6px",marginBottom:"12px",flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:"4px",padding:"5px 10px",borderRadius:"5px",border:`1px solid ${B}`,background:C,fontSize:"11px",color:"#a1a1aa",flex:1,minWidth:"120px"}}><Ic n="search" s={12}/>Search...</div>{["Last 7 days","All agents","All statuses"].map(f=><div key={f} style={{padding:"5px 10px",borderRadius:"5px",border:`1px solid ${B}`,fontSize:"10px",color:"#a1a1aa",display:"flex",alignItems:"center",gap:"3px"}}><Ic n="filter" s={10}/>{f}</div>)}</div>
<div style={{display:"grid",gridTemplateColumns:sel?"1fr 1fr":"1fr",gap:"10px"}}>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",overflow:"hidden"}}><table style={{width:"100%",fontSize:"10px",borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${B}`}}>{["Phone","Agent","Duration","Status","Outcome","Date"].map(h=><th key={h} style={{padding:"6px 8px",textAlign:"left",color:M,fontWeight:500}}>{h}</th>)}</tr></thead><tbody>{calls.map(c=><tr key={c.id} onClick={()=>setSel(c.id===sel?null:c.id)} style={{borderBottom:`1px solid ${B}`,cursor:"pointer",background:c.id===sel?`${T}06`:"transparent"}}><td style={{padding:"6px 8px",color:X,fontFamily:"monospace"}}>{c.ph}</td><td style={{padding:"6px 8px",color:"#d4d4d8"}}>{c.ag}</td><td style={{padding:"6px 8px",color:"#a1a1aa"}}>{c.dur}</td><td style={{padding:"6px 8px"}}><Bd color={sc[c.st]}>{c.st.replace("_"," ")}</Bd></td><td style={{padding:"6px 8px",color:c.out==="Task success"?"#4ade80":c.out==="Transferred"?"#f59e0b":"#52525b"}}>{c.out}</td><td style={{padding:"6px 8px",color:"#52525b"}}>{c.dt}</td></tr>)}</tbody></table></div>
{sel&&<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"14px"}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:"10px"}}><div><div style={{fontSize:"13px",fontWeight:500,color:"#fafafa"}}>+1***8860</div><div style={{fontSize:"10px",color:M}}>Sales Qualifier · 2m 34s</div></div><div style={{display:"flex",gap:"4px",alignItems:"center"}}><Bd color="green">Answered</Bd><div onClick={()=>setSel(null)} style={{cursor:"pointer",color:"#3f3f46"}}><Ic n="x" s={14}/></div></div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"4px",marginBottom:"10px"}}>{[{l:"Ring",v:"4s"},{l:"Talk",v:"2m 30s"},{l:"Latency",v:"180ms"}].map(m=><div key={m.l} style={{background:C,borderRadius:"5px",padding:"6px",textAlign:"center"}}><div style={{fontSize:"9px",color:M}}>{m.l}</div><div style={{fontSize:"12px",fontWeight:500,color:X}}>{m.v}</div></div>)}</div>
<div style={{fontSize:"10px",fontWeight:500,color:M,marginBottom:"6px"}}>Transcript</div>
{[{s:"agent",t:"Hi! Thanks for calling Acme."},{s:"caller",t:"I saw your ad about enterprise."},{s:"agent",t:"Great! Can I ask about your team size?"},{s:"caller",t:"About 50 people, customer support."}].map((m,i)=><div key={i} style={{display:"flex",gap:"6px",marginBottom:"5px"}}><div style={{width:"4px",height:"4px",borderRadius:"50%",background:m.s==="agent"?T:"#60a5fa",marginTop:"4px",flexShrink:0}}/><div><div style={{fontSize:"9px",color:"#3f3f46"}}>{m.s==="agent"?"Agent":"Caller"}</div><div style={{fontSize:"11px",color:"#d4d4d8",lineHeight:1.3}}>{m.t}</div></div></div>)}
<div style={{marginTop:"8px",padding:"6px 8px",background:C,borderRadius:"5px",display:"flex",alignItems:"center",gap:"6px"}}><Ic n="play" s={12}/><div style={{flex:1,height:"3px",background:B,borderRadius:"2px"}}><div style={{width:"40%",height:"100%",background:T,borderRadius:"2px"}}/></div><span style={{fontSize:"9px",color:M}}>1:02/2:34</span></div>
</div>}</div>
</Fr>);}

function F8(){return(<Fr title="/dashboard" sub="Feature 8 — Overview dashboard (command center)">
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"6px",marginBottom:"12px"}}>{[{l:"Active agents",v:"4",s:"2 published",c:T},{l:"Phone numbers",v:"3",s:"2 verified",c:"#60a5fa"},{l:"Active campaigns",v:"1",s:"750/1,000 calls",c:"#a78bfa"},{l:"Calls (24h)",v:"127",s:"↑ 23% vs yesterday",c:"#4ade80"}].map(k=><div key={k.l} style={{background:S,borderRadius:"8px",padding:"10px",border:`1px solid ${B}`}}><div style={{fontSize:"10px",color:M,marginBottom:"4px"}}>{k.l}</div><div style={{fontSize:"20px",fontWeight:600,color:"#fafafa",marginBottom:"2px"}}>{k.v}</div><div style={{fontSize:"10px",color:k.c}}>{k.s}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px",marginBottom:"12px"}}>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"12px",fontWeight:500,color:X,marginBottom:"10px"}}>Recent activity</div>{[{i:"zap",t:"Sales Qualifier published",d:"2h ago",c:T},{i:"play",t:"Q2 Outreach launched",d:"5h ago",c:"#a78bfa"},{i:"phone",t:"+15541361716 imported",d:"yesterday",c:"#60a5fa"},{i:"bot",t:"NPS Survey created",d:"2 days ago",c:"#f59e0b"}].map((e,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:"8px",padding:"6px 0",borderBottom:i<3?`1px solid ${B}`:"none"}}><div style={{width:"24px",height:"24px",borderRadius:"5px",background:`${e.c}12`,display:"flex",alignItems:"center",justifyContent:"center",color:e.c,flexShrink:0}}><Ic n={e.i} s={11}/></div><div style={{flex:1}}><div style={{fontSize:"11px",color:"#d4d4d8"}}>{e.t}</div><div style={{fontSize:"9px",color:"#3f3f46"}}>{e.d}</div></div></div>)}</div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"12px",fontWeight:500,color:X,marginBottom:"10px"}}>Quick actions</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"6px"}}>{[{l:"Create agent",i:"bot",d:"Build voice AI"},{l:"Launch campaign",i:"play",d:"Outbound calling"},{l:"Import number",i:"phone",d:"Add SIP trunk"},{l:"View analytics",i:"bar",d:"Monitor calls"}].map(a=><div key={a.l} style={{background:C,border:`1px solid ${B}`,borderRadius:"6px",padding:"10px"}}><div style={{color:T,marginBottom:"6px"}}><Ic n={a.i} s={14}/></div><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"2px"}}>{a.l}</div><div style={{fontSize:"9px",color:"#52525b"}}>{a.d}</div></div>)}</div></div></div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"8px"}}>Call volume — last 7 days</div><div style={{display:"flex",alignItems:"flex-end",gap:"5px",height:"60px"}}>{[45,62,78,95,120,140,127].map((v,i)=><div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:"3px"}}><div style={{width:"100%",height:`${(v/140)*100}%`,background:i===6?T:`${T}40`,borderRadius:"3px 3px 0 0",minHeight:"3px"}}/><span style={{fontSize:"8px",color:"#3f3f46"}}>{["M","T","W","T","F","S","S"][i]}</span></div>)}</div></div>
</Fr>);}

function F9(){return(<Fr title="/dashboard/campaign/camp_001" sub="Feature 9 — Campaign detail & results view">
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><div><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"3px"}}><span style={{fontSize:"16px",fontWeight:600,color:"#fafafa"}}>Q2 Outreach Campaign</span><Bd color="teal">In progress</Bd></div><div style={{fontSize:"11px",color:M}}>Started Apr 5 · Sales Qualifier v1 · +15541361716</div></div><div style={{padding:"5px 12px",fontSize:"11px",borderRadius:"5px",border:`1px solid #f59e0b40`,color:"#f59e0b",display:"flex",alignItems:"center",gap:"3px"}}><Ic n="pause" s={11}/>Pause</div></div>
<div style={{background:S,borderRadius:"6px",padding:"6px 10px",marginBottom:"12px",border:`1px solid ${B}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"4px"}}><span style={{fontSize:"11px",color:"#d4d4d8"}}>Progress</span><span style={{fontSize:"11px",color:T,fontWeight:500}}>750 / 1,000</span></div><div style={{height:"5px",background:B,borderRadius:"3px"}}><div style={{width:"75%",height:"100%",background:T,borderRadius:"3px"}}/></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:"6px",marginBottom:"12px"}}>{[{l:"Contacts",v:"1,000"},{l:"Calls made",v:"750"},{l:"Answer rate",v:"62%",c:"#4ade80"},{l:"Avg duration",v:"2m 15s"},{l:"Task success",v:"78%",c:T}].map(s=><div key={s.l} style={{background:S,borderRadius:"6px",padding:"8px",textAlign:"center",border:`1px solid ${B}`}}><div style={{fontSize:"9px",color:M,marginBottom:"3px"}}>{s.l}</div><div style={{fontSize:"14px",fontWeight:600,color:s.c||"#fafafa"}}>{s.v}</div></div>)}</div>
<div style={{display:"flex",gap:"1px",marginBottom:"12px",background:B,borderRadius:"5px",overflow:"hidden"}}>{["Results","Call log","Settings"].map((t,i)=><div key={t} style={{flex:1,textAlign:"center",padding:"6px 0",fontSize:"11px",background:i===0?`${T}12`:C,color:i===0?T:"#52525b"}}>{t}</div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px"}}><div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"8px"}}>Outcome breakdown</div><div style={{display:"flex",alignItems:"center",gap:"12px"}}><div style={{width:"60px",height:"60px",borderRadius:"50%",background:`conic-gradient(#4ade80 0% 48%,#60a5fa 48% 80%,#a78bfa 80% 85%,#ef4444 85% 87%,#f59e0b 87% 100%)`,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:"38px",height:"38px",borderRadius:"50%",background:S,display:"flex",alignItems:"center",justifyContent:"center",fontSize:"9px",color:X,fontWeight:500}}>750</div></div><div style={{fontSize:"10px",color:"#a1a1aa",lineHeight:1.8}}>Answered 48%<br/>No answer 32%<br/>Voicemail 5%<br/>Transferred 13%</div></div></div>
<div style={{background:S,border:`1px solid ${B}`,borderRadius:"8px",padding:"12px"}}><div style={{fontSize:"11px",fontWeight:500,color:X,marginBottom:"8px"}}>Calls per hour</div><div style={{display:"flex",alignItems:"flex-end",gap:"2px",height:"50px"}}>{[0,0,0,0,0,0,0,0,12,28,45,52,60,48,55,42,38,30,15,0,0,0,0,0].map((v,i)=><div key={i} style={{flex:1,height:v>0?`${(v/60)*100}%`:"2px",background:v>0?(i>=9&&i<=17?T:`${T}40`):B,borderRadius:"1px 1px 0 0"}}/>)}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:"3px"}}>{["12am","6am","12pm","6pm","12am"].map(l=><span key={l} style={{fontSize:"8px",color:"#3f3f46"}}>{l}</span>)}</div></div></div>
</Fr>);}

export default function AllScreens(){return(<div style={{fontFamily:"'DM Sans',system-ui,sans-serif",background:"#08080a",color:X,padding:"20px 16px"}}>
<div style={{textAlign:"center",marginBottom:"8px"}}><h1 style={{fontSize:"18px",fontWeight:600,color:"#fafafa",margin:"0 0 4px"}}>Agent Studio UX — all 9 feature screens</h1><p style={{fontSize:"12px",color:M,margin:0}}>Complete reference for PRD screenshots — attach to Claude Code</p></div>
<Sl>Feature 1 — setup wizard onboarding</Sl><F1/>
<Sl>Feature 2 — campaign stepper wizard</Sl><F2/>
<Sl>Feature 3 — agent editor + test panel</Sl><F3/>
<Sl>Feature 4 — provider-guided phone setup</Sl><F4/>
<Sl>Feature 5 — actionable analytics</Sl><F5/>
<Sl>Feature 6 — role-based sidebar + impersonation</Sl><F6/>
<Sl>Feature 7 — call history + transcript viewer</Sl><F7/>
<Sl>Feature 8 — overview dashboard</Sl><F8/>
<Sl>Feature 9 — campaign detail + results</Sl><F9/>
</div>);}
